CREATE TABLE Consultas(
	`Cod_Paciente` int NOT NULL,
	`Cons_Paciente` int NOT NULL,
	`Dt_Atend` datetime(3) NULL,
	`Hr_Atend` datetime(3) NULL,
	`Cod_Med` int NULL,
	`Cod_Ubs` int NULL,
	`Queixa_principal` varchar(255) NULL,
	`HMA` varchar(255) NULL,
	`Suspeita` varchar(255) NULL,
	`Exame_Fisico` varchar(255) NULL,
	`Justif_Exames` varchar(255) NULL,
	`Justif_Proced` varchar(255) NULL,
	`Cardio` varchar(1) NULL,
	`Respira` varchar(1) NULL,
	`Cranio` varchar(1) NULL,
	`Abdome` varchar(1) NULL,
	`Extremidade` varchar(1) NULL,
	`Data_Inter` Datetime NULL,
	`PA` varchar(7) NULL,
	`FC` varchar(3) NULL,
	`Peso` decimal(18, 2) NULL,
	`Altura` decimal(18, 2) NULL,
	`Temperatura` decimal(18, 2) NULL,
	`Hora_Ini_Atend` datetime(3) NULL,
	`Hora_Fim_Atend` datetime(3) NULL,
	`CodigoGrupoAtendimento` int NULL,
	`Codigo_Especialidade` int NULL,
	`Codigo_CBO` int NULL,
	`Glicosimetria` smallint NULL,
	`IP` varchar(20) NULL,
	`Versao_DataHora` varchar(40) NULL,
	`Num_AtendimentoPS` varchar(10) NULL,
	`FreqResp` int NULL,
	`Glasgow` int NULL,
	`CBO` varchar(10) NULL,
 CONSTRAINT `PK_Consultas` PRIMARY KEY 
(
	`Cod_Paciente` ASC,
	`Cons_Paciente` ASC
) 
);